---
title: "2021-08-11-Optimal-only-clustering-AKS"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Set up the environment and import the data and metadata
```{r setup}
library(ggplot2)
library(forcats)
library(readxl)
library(readr)
library(pheatmap)
library(factoextra)
library(reshape2)
library(BBmisc)

 #List of genes in VNG_RS format.Data frame with column name Gene. 
 #Normalised counts csv file generated by DEseq2.

Genelist = read_excel("TableS4_diffexpr-AKS-nonredundant-noCombinatorial-_v2_SSAug26.xlsx", sheet = "KO_sigresults")
Expression=read_csv("normalised_counts_21samples.csv")

```

# mean/variance normalize and subset the data to include genes differentially expressed in low salt conditions
```{r normalisation}

    
  #Exclude all genes differentially expressed in optimal salt
  listofgenes=Genelist[Genelist$Low_padj==1,]
  listofgenes=listofgenes$Gene
  l=length(listofgenes)
  
  
  allexpr=as.data.frame(matrix(nrow=l,ncol=4))
  
  
  for (i in (1:l)) {
    
    #Find the gene in the normalised count file
    j=which(Expression$X1==listofgenes[i])

    expr = as.numeric(vector(length=4))
    
    #Get avg expression for this gene from bioreps of 4 conditions
    #mean/SD normalisation of each gene for visualisation.
    
    expr[1]=mean(as.numeric(Expression[j,2:7]))
    expr[2]=mean(as.numeric(Expression[j,8:12]))
    expr[3]=mean(as.numeric(Expression[j,13:18]))
    expr[4]=mean(as.numeric(Expression[j,19:22]))
    normexpr=normalize(expr,method="standardize")

    allexpr[i,]=normexpr
    
  }
  
  rownames(allexpr)=listofgenes
  colnames(allexpr)=c("WT optimal","WT low","∆hpyA optimal","∆hpyA low")

```
  
# cluster using Kmeans and make heatmap (figure 6)
```{r heatmap}
  #kmeans clustering of the expression patterns of all genes.
  #no  of clusters deterimned using fviz_nbclust function.
pdf("optimal_heatmap.pdf", height = 8, width = 16)

  clustcalc=fviz_nbclust(allexpr,kmeans,method="silhouette")
  nclust=which.max(clustcalc$data$y)
  #nclust=5
  clustexpr=kmeans(allexpr,nclust)
  clustexpr2=cbind(allexpr,clustexpr$cluster)
  clustexpr2$names=rownames(allexpr)
  o=order(clustexpr$cluster)
  clustexpr2=clustexpr2[o,]
  #print(pheatmap(clustexpr2[,1:4],cluster_cols = FALSE,cluster_rows = FALSE))
   print(pheatmap(clustexpr2[,1:4],cluster_cols = FALSE, cluster_rows = TRUE, angle_col = "45", fontsize_col = 8, fontsize_row = 4))
dev.off()  
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
