---
title: "Nooptimal_clustering-AKS"
author: "Saaz Sakrikar-Amy Schmid"
date: "3/9/2021"
output: html_document
editor_options: 
  chunk_output_type: inline
---

#Set up the environment and import the data and metadata
```{r setup}
library(ggplot2)
library(forcats)
library(readxl)
library(readr)
library(pheatmap)
library(factoextra)
library(reshape2)
library(BBmisc)

 #List of genes in VNG_RS format.Data frame with column name Gene. 
 #Normalised counts csv file generated by DeSeq2.

#Genelist=read_excel("June2021_diffexpr_COGs_21samps.xlsx")
Genelist = read_excel("TableS4_diffexpr-AKS-nonredundant-noCombinatorial-_v2_SSAug26.xlsx", sheet = "KO_sigresults")
Expression=read_csv("normalised_counts_21samples.csv")

```

# mean/variance normalize and subset the data to include genes differentially expressed in low salt conditions
```{r normalisation}

    
  #Exclude all genes differentially expressed in optimal salt
  listofgenes=Genelist[Genelist$Optimal_padj==1,]
  listofgenes=listofgenes$Gene
  l=length(listofgenes)
  
  
  allexpr=as.data.frame(matrix(nrow=l,ncol=4))
  
  
  for (i in (1:l)) {
    
    #Find the gene in the normalised count file
    j=which(Expression$X1==listofgenes[i])

    expr = as.numeric(vector(length=4))
    
    #Get avg expression for this gene from bioreps of 4 conditions
    #mean/SD normalisation of each gene for visualisation.
    
    expr[1]=mean(as.numeric(Expression[j,2:7]))
    expr[2]=mean(as.numeric(Expression[j,8:12]))
    expr[3]=mean(as.numeric(Expression[j,13:18]))
    expr[4]=mean(as.numeric(Expression[j,19:22]))
    normexpr=normalize(expr,method="standardize")

    allexpr[i,]=normexpr
    
  }
  
  rownames(allexpr)=listofgenes
  colnames(allexpr)=c("WT optimal","WT low","∆hpyA optimal","∆hpyA low")

```
  
# cluster using Kmeans and make heatmap (figure 6)
```{r heatmap}
  #kmeans clustering of the expression patterns of all genes.
  #no  of clusters deterimned using fviz_nbclust function.
pdf("low_heatmap.pdf", height = 8, width = 16)

  clustcalc=fviz_nbclust(allexpr,kmeans,method="silhouette")
  nclust=which.max(clustcalc$data$y)
  #nclust=5
  clustexpr=kmeans(allexpr,nclust)
  clustexpr2=cbind(allexpr,clustexpr$cluster)
  clustexpr2$names=rownames(allexpr)
  o=order(clustexpr$cluster)
  clustexpr2=clustexpr2[o,]
  #print(pheatmap(clustexpr2[,1:4],cluster_cols = FALSE,cluster_rows = FALSE))
   print(pheatmap(clustexpr2[,1:4],cluster_cols = FALSE, cluster_rows = TRUE, angle_col = "45", fontsize_col = 8, fontsize_row = 4))
dev.off()  
```




```{r clusteredlines,warning=FALSE}
#Line plots for each cluster.

for (i in (1:nclust)) {
  clustexpr3=clustexpr2[clustexpr2$`clustexpr$cluster`==i,]
  clustexpr3=clustexpr3[,-5]
  clustexpr3$names=rownames(clustexpr3)
  clustexpr3=melt(clustexpr3, id.vars="names")
  
  print(ggplot(clustexpr3,aes(x=fct_inorder(variable),y=value))+geom_line(aes(group=names))+theme_bw()+theme(legend.position="none"))
}

```

```{r selectedclusters, warning=FALSE}
  
#Subclustering within each cluster made above.
  


  for (i in (1:nclust)) {
    #kmeans clustering within the selected cluster.
   
    
    clustexpr4=clustexpr2[clustexpr2$`clustexpr$cluster`==i,]
    clustexpr4=clustexpr4[,-5]
    clustexpr4=clustexpr4[,-5]
    clustcalc2=fviz_nbclust(clustexpr4,kmeans,method="silhouette")
    nclust2=which.max(clustcalc2$data$y)
    #nclust2=2
    clustexpr5=kmeans(clustexpr4,nclust2)
    clustexpr6=cbind(clustexpr4,clustexpr5$cluster)
    clustexpr6$names=rownames(clustexpr4)
    o=order(clustexpr5$cluster)
    clustexpr6=clustexpr6[o,]
    
    
    print(pheatmap(clustexpr6[,1:4],cluster_cols = FALSE,cluster_rows = TRUE))
    
    
    for (j in (1:nclust2)) {
      #visualisation of each subcluster.
      clustexpr7=clustexpr6[clustexpr6$`clustexpr5$cluster`==j,]
      clustexpr7=clustexpr7[,-5]
      clustexpr7$names=rownames(clustexpr7)
      clustexpr7=melt(clustexpr7, id.vars="names")
      l2=length(clustexpr7$variable)
      conditionasnumeric=as.numeric(vector(length=l2))
      
      for (k in (1:l2)) {
        #using numbers as proxy for condition to allow the "ribbon" line point using geom_smooth
        if (clustexpr7$variable[k]=="WTCM") {conditionasnumeric[k]=1}
        if (clustexpr7$variable[k]=="WTM") {conditionasnumeric[k]=2}
        if (clustexpr7$variable[k]=="KOCM") {conditionasnumeric[k]=3}
        if (clustexpr7$variable[k]=="KOM") {conditionasnumeric[k]=4}
      }
    
      clustexpr7=cbind(clustexpr7,conditionasnumeric)
      colnames(clustexpr7)[4]="Conditionasnumeric"
      print(ggplot(clustexpr7,aes(x=Conditionasnumeric,y=value))+geom_line(alpha=0.3,aes(group=names))+geom_smooth()+theme_bw()+theme(legend.position="none"))
      
      print(ggplot(clustexpr7,aes(x=fct_inorder(variable),y=value))+geom_boxplot(alpha=0.5,aes(fill=variable))+geom_jitter(size=1,width=0.25)+theme_bw()+scale_fill_manual(values=c("black","grey","red","lightcoral")))
      
      
    # make dot plots of each subcluster (final supplementary Figure s)  
   # pdf(paste("dot_cluster_plots_low", i, ".pdf", sep=""), width = 6,  height = 4)
      print(ggplot(clustexpr7,aes(x=fct_inorder(variable),y=value))+geom_jitter(size=1.25,width=0.25,aes(color=variable))+theme_bw()+scale_color_manual(values=c("blue","cadetblue3","red","lightcoral"))+stat_summary(fun=median,geom="crossbar",width=0.5,aes(color=variable)))
     # dev.off()
    }
   
  }

#looks like dot plots are the clearest, but more expanded representation of expression patterns for individual genes (presented in supplementary figures). Heat maps are the most compact, clear representation appropriate for main text figure.
```
# Main text Figure 6 - heat maps
```{r}
for (i in (1:nclust)) {
    #kmeans clustering within the selected cluster.
   
    
    clustexpr4=clustexpr2[clustexpr2$`clustexpr$cluster`==i,]
    clustexpr4=clustexpr4[,-5]
    clustexpr4=clustexpr4[,-5]
    clustcalc2=fviz_nbclust(clustexpr4,kmeans,method="silhouette")
    nclust2=which.max(clustcalc2$data$y)
    #nclust2=2
    clustexpr5=kmeans(clustexpr4,nclust2)
    clustexpr6=cbind(clustexpr4,clustexpr5$cluster)
    clustexpr6$names=rownames(clustexpr4)
    o=order(clustexpr5$cluster)
    clustexpr6=clustexpr6[o,]
    
    pdf(paste("heatmap_low", i, ".pdf", sep=""), width = 6,  height = 6)
    print(pheatmap(clustexpr6[,1:4],cluster_cols = FALSE,cluster_rows = TRUE, angle_col = "45", fontsize_col = 8, fontsize_row = 6))
    dev.off()
}
```
